.Dd November 10, 2012
.Dt GtMixer 1
.Os
.Sh NAME
.Nm gtmixer
.Nd graphical set/display soundcard mixer values

.Sh DESCRIPTION
The
.Nm
utility is used to set and display soundcard mixer device levels.
.Nm
based on standart mixer(8) utility.
.Sh FILES
.Bl -tag -width /usr/local/sbin/gtmixer -compact
.It Pa /usr/local/sbin/gtmixer
the default mixer device
.El
.Sh SEE ALSO
.Xr mixer 8
.Sh AUTHORS
.An -nosplit
Source by
.An Stanislav Putrya Aq vagner@bsdway.ru
This
manual page was written by
.An Stanislav Putrya Aq vagner@bsdway.ru .
